name: OrangeFox - Build X688C

on:
  workflow_dispatch:

jobs:
  build:
    name: Build OFRP X688C
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      KERNEL_URL: https://drive.google.com/uc?export=download&id=1WyIQgVADu5zF8MD6zmeblOOnReoGJxqS
      DEVICE_TREE: https://github.com/TeamWin/android_device_infinix_x688b
      DEVICE_TREE_BRANCH: android-12.1
      DEVICE_PATH: device/infinix/x688b
      DEVICE_NAME: x688b
      MANIFEST_BRANCH: 12.1
      LDCHECK: system/bin/hwservicemanager
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Clean-up + Swap
      uses: rokibhasansagar/slimhub_actions@main
    - uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 24
      
    - name: Build Environment
      run: |
        sudo apt update -y
        git clone https://gitlab.com/OrangeFox/misc/scripts
        sudo bash scripts/setup/android_build_env.sh
      
    - name: Download boot.img
      run: wget -O ${GITHUB_WORKSPACE}/boot.img "${{ env.KERNEL_URL }}"
      
    - name: Set-up Manifest
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/OrangeFox
        cd ${GITHUB_WORKSPACE}/OrangeFox
        git clone https://gitlab.com/OrangeFox/sync.git
        cd sync
        ./orangefox_sync.sh --branch ${{ env.MANIFEST_BRANCH }} --path ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ env.MANIFEST_BRANCH }}

    - name: Clone Device Tree + Inject Kernel
      run: |
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ env.MANIFEST_BRANCH }}
        git clone ${{ env.DEVICE_TREE }} -b ${{ env.DEVICE_TREE_BRANCH }} ./${{ env.DEVICE_PATH }}
        cp ${GITHUB_WORKSPACE}/boot.img ./${{ env.DEVICE_PATH }}/kernel

    - name: Build OrangeFox
      run: |
        cd ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ env.MANIFEST_BRANCH }}
        source build/envsetup.sh
        lunch twrp_${{ env.DEVICE_NAME }}-eng
        mka recoveryimage

    - name: Upload
      if: success()
      uses: softprops/action-gh-release@v1
      with:
        files: ${GITHUB_WORKSPACE}/OrangeFox/fox_${{ env.MANIFEST_BRANCH }}/out/target/product/${{ env.DEVICE_NAME }}/OrangeFox*.img
        name: OrangeFox-X688C // ${{ env.MANIFEST_BRANCH }}
        tag_name: x688c-${{ github.run_id }}
